### ISSUE TITLE
Add user 'shiny' to group 'vagrant' on creation

### ISSUE THREAD

**Issue by jsramos** [leondutoit/shiny-server-on-ubuntu#4]
When deploying shiny apps to this shiny server, and those apps require access to APIs via OAuth, it is necessary to cache the token locally, but doing so gives an error because the /vagrant/apps directory is owned by group 'vagrant', and user 'shiny' is not a member of such group. I fixed the error by adding user 'shiny' to group vagrant with this line [sudo usermod -a -G vagrant shiny]. Care to add this line to your Vagrant file? Thanks. This vagrant box saved me hours of struggle!

**Comment by leondutoit** [comment]
Good catch! I'll add your suggestion, thanks :)

**Comment by leondutoit** [comment]
@jsramos, it would be great if you could test this with your app so I can be sure it works for you before closing.

**Comment by xuxoramos** [comment]
Definitely. Lemme try it tonight and report back!

On Tue, Dec 29, 2015 at 5:47 AM, Leon du Toit notifications@github.com
wrote:

> @jsramos https://github.com/jsramos, it would be great if you could
> test this with your app so I can be sure it works for you before closing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/leondutoit/shiny-server-on-ubuntu/issues/4#issuecomment-167772370
> .

## 

"Let my armies be the rocks and the trees, and the birds in the sky."
                         --Dr. Henry Jones Sr., PhD
